// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvNKN_LC_8--I13b0vG9GJ9nONQNBZ3Y',
    appId: '1:607726452060:web:b949e601a1c491e0d95599',
    messagingSenderId: '607726452060',
    projectId: 'kkbp-97108',
    authDomain: 'kkbp-97108.firebaseapp.com',
    storageBucket: 'kkbp-97108.firebasestorage.app',
    measurementId: 'G-R3STWQ5GYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1OIYSg4A4KpRyi0P7XhezrkHxYffLoI',
    appId: '1:607726452060:android:d21922c9643bfe76d95599',
    messagingSenderId: '607726452060',
    projectId: 'kkbp-97108',
    storageBucket: 'kkbp-97108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvQ4bMFHAIGFP2wa7q9Pu1P9_pJesSam4',
    appId: '1:607726452060:ios:83bd1218bb035733d95599',
    messagingSenderId: '607726452060',
    projectId: 'kkbp-97108',
    storageBucket: 'kkbp-97108.firebasestorage.app',
    iosBundleId: 'com.charlotte.kkb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvQ4bMFHAIGFP2wa7q9Pu1P9_pJesSam4',
    appId: '1:607726452060:ios:6250c3ba3a1140f2d95599',
    messagingSenderId: '607726452060',
    projectId: 'kkbp-97108',
    storageBucket: 'kkbp-97108.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvNKN_LC_8--I13b0vG9GJ9nONQNBZ3Y',
    appId: '1:607726452060:web:da7a1b7c294058b6d95599',
    messagingSenderId: '607726452060',
    projectId: 'kkbp-97108',
    authDomain: 'kkbp-97108.firebaseapp.com',
    storageBucket: 'kkbp-97108.firebasestorage.app',
    measurementId: 'G-HBXK9R74KF',
  );
}
